module.exports = {
    GET_LOGIN_INFO_REQUEST: 'loginInfo/GET_LOGIN_INFO_REQUEST',
    GET_LOGIN_INFO_SUCCESS: 'loginInfo/GET_LOGIN_INFO_SUCCESS',
    GET_LOGIN_INFO_FAIL: 'loginInfo/GET_LOGIN_INFO_FAIL',
}